// app/api/asset-factory/export/route.ts

import { NextRequest, NextResponse } from "next/server"
import { currentUser } from "@clerk/nextjs/server"
import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

export async function POST(req: NextRequest) {
  try {
    const user = await currentUser()
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

    const { projectId, exportType } = await req.json()

    const project = await prisma.assetFactoryProject.findFirst({
      where: { id: projectId, userId: user.id },
      include: { outputs: { orderBy: { phase: "asc" } } },
    })

    if (!project) return NextResponse.json({ error: "Project not found" }, { status: 404 })

    if (exportType === "json") {
      const jsonData: Record<string, Record<string, unknown>> = {}
      for (const output of project.outputs) {
        if (!jsonData[output.phase]) jsonData[output.phase] = {}
        try {
          jsonData[output.phase][output.sectionTitle] = output.format === "json"
            ? JSON.parse(output.content)
            : output.content
        } catch {
          jsonData[output.phase][output.sectionTitle] = output.content
        }
      }
      return new NextResponse(JSON.stringify(jsonData, null, 2), {
        headers: {
          "Content-Type": "application/json",
          "Content-Disposition": `attachment; filename="asset-factory-${project.id}.json"`,
        },
      })
    }

    if (exportType === "markdown") {
      const phaseLabels: Record<string, string> = {
        strategic_intelligence: "🧠 Phase 1 — Strategic Intelligence",
        offer_engineering: "💰 Phase 2 — Offer Engineering",
        digital_product: "📚 Phase 3 — Digital Product Builder",
        webinar_engine: "🎙️ Phase 4 — Webinar Engine",
        ai_video_content: "🎬 Phase 5 — AI Video Content",
        funnel_crm_assets: "🔧 Phase 6 — Funnel + CRM Assets",
      }

      let md = `# ${project.title}\n\nGenerated by WebinarForge AI Asset Factory™\n\n---\n\n`

      const grouped: Record<string, typeof project.outputs> = {}
      for (const output of project.outputs) {
        if (!grouped[output.phase]) grouped[output.phase] = []
        grouped[output.phase].push(output)
      }

      for (const [phase, outputs] of Object.entries(grouped)) {
        md += `## ${phaseLabels[phase] || phase}\n\n`
        for (const output of outputs) {
          md += `### ${output.sectionTitle.replace(/_/g, " ").toUpperCase()}\n\n`
          if (output.format === "json") {
            try {
              const parsed = JSON.parse(output.content)
              if (Array.isArray(parsed)) {
                parsed.forEach((item: string, i: number) => {
                  md += `${i + 1}. ${item}\n`
                })
              } else {
                md += `${JSON.stringify(parsed, null, 2)}\n`
              }
            } catch {
              md += `${output.content}\n`
            }
          } else {
            md += `${output.content}\n`
          }
          md += "\n---\n\n"
        }
      }

      return new NextResponse(md, {
        headers: {
          "Content-Type": "text/markdown",
          "Content-Disposition": `attachment; filename="asset-factory-${project.id}.md"`,
        },
      })
    }

    return NextResponse.json({ error: "Unsupported export type" }, { status: 400 })
  } catch (err: any) {
    console.error("Export error:", err)
    return NextResponse.json({ error: "Export failed" }, { status: 500 })
  }
}
